# K-Nearest Neighbors


### 1. Import useful package

In [58]:
from sklearn.datasets import load_iris
from sklearn.metrics import confusion_matrix, accuracy_score, plot_confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt


### 2. Load dataset and make dataframe

In [51]:
df = load_iris()

In [53]:
data = np.append(df.data,df.target.reshape((150,1)),axis=1)
columns = list(df.feature_names)+['target']
dataframe = pd.DataFrame(data = data,columns=columns)
dataframe.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

### 3. Split data in Training and testing set

In [11]:
X = df.data
Y = df.target

In [21]:

x_train,x_test,y_train,y_test = train_test_split(X,Y)

### 4. Create Model and Train

In [23]:
knn = KNeighborsClassifier(n_neighbors=4)

In [24]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [55]:
p = knn.predict([x_train[0]])
print(df.target_names[p])

['virginica']


### 5. Accuracy and confusion matrix

In [57]:
y_p = knn.predict(x_test)
acc = accuracy_score(y_test,y_p)
con_mat = confusion_matrix(y_test,y_p)
print(f'Accuracy Score = {acc} .')
print(f'Confusion Matrix :\n{con_mat}')

Accuracy Score = 0.9473684210526315 .
Confusion Matrix :
[[15  0  0]
 [ 0 13  1]
 [ 0  1  8]]


---